services:
  - type: web
    name: gracebridge
    env: node
    rootDir: gracebridge
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: COHERE_API_KEY
        sync: false 